### PR TITLE
allow v12 and v13 of websockets

### PR DESCRIPTION
**Pull request by MichaelMKKelly**
avoids dependency clash in downstream projects as described in this issue https://github.com/baking-bad/pysignalr/issues/23

### CODE REVIEW

**Comment by olalid** [comment]
I do not think it is that simple. The import is done using the legacy path which was removed in 13.0.
So the code of the lib has to change too...

**Comment by olalid** [comment]
Here: https://github.com/baking-bad/pysignalr/blob/b207c6e2602e3501e7f1c023aed93f52814132bd/src/pysignalr/__init__.py#L11

**Comment by olalid** [comment]
Yeah, you might be right. As you say 14.0 is the first version where legacy is not default.
Need to verify that the error handling still works though, since it is crucial for us (in pyeasee) to not cause havoc on the server side during reconnects (which has been a problem since we started using pysignalr until we found the issue and patched it).

In any case, at the moment, we are not getting any responses from the developers of this project, so if that situation does not change in the coming week my plan is to import the code of this project in to pyeasee and make the changes we need.

**Comment by MichaelMKKelly** [comment]
indeed, you should note that in HA 2024.12 version 13.1 is being forced https://github.com/home-assistant/core/pull/131039 so if there is an issue with pyeasee running on that version you are likely to see it in easee_hass and hear about it. so you may want to have a plan in place by then (04-DEC). currently the issue is that it breaks a core integration but they are forcing the issue so core stuff works and custom have to fix (which is fair)

**Comment by MichaelMKKelly** [comment]
@droserasprout from what I can tell it doesn't have any issues when running under the versions this change will include. and there are no breaking changes ton cause issues. and down stream projects seem to operate fine using the library when forced to a higher versions.

@olalid probably uses the code base more than me though and may be better suited to confirm?

**Comment by olalid** [comment]
I did a very brief test earlier today, but to really confirm I need a bit more time to check.

But, is the syntax in the change correct? It is now:
websockets = "websockets>=12.0,<14"
Should it not be:
websockets = ">=12.0,<14"
?

**Comment by MichaelMKKelly** [comment]
@olalid entirely right, I have updated and should be good now

**Comment by olalid** [comment]
I have now verified that it works at least in my environment with all versions between 12.0 to 13.1.

Actually it seems to work also with 14.0, which is a bit surprising, but since the import looks like this:
from websockets.client import WebSocketClientProtocol, connect
It seems like that triggers the legacy implementation to be used.
To get the new asyncio version you would need to do
from websockets import etc...
or
from websockets.asyncio.client import etc...
See client API section here: https://websockets.readthedocs.io/en/stable/howto/upgrade.html#client-apis

I am happy to leave as is in this PR for now though, and I can provide a PR at some later point to change to new asyncio version of the APIs where we can loosen the requirements even further.

@droserasprout it is now back in your hands, let me know if you need something more to continue.

**Comment by olalid** [comment]
@droserasprout, what are the chances we will get a new release before December 4?
That is when things will stop working for us, unless we get a release that supports 13.x websockets.
If there is anything I can do to help you move forward more quickly, just tell me...

**Comment by droserasprout** [comment]
@olalid I'm gonna try to wrap it up in the next few days.

**Pull request merged**
